final List<String> skillsList = [
  'Flutter',
  'Android Development',
  'iOS Development',
  'React',
  'React Native',
  'Next.js',
  'Node.js',
  'Backend Development',
  'API Development',
  'Firebase',
  'Supabase',
  'SQL',
  'MongoDB',
  'DevOps',
  'Docker',
  'CI/CD',
  'Git',
  'Software Architecture',
  'Testing / QA',
  'Cybersecurity',
  'Machine Learning',
  'AI Development',
];